# Generated by Django 3.0.2 on 2020-03-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
